title: Open Knowledge Labs Handbook
short_title: Labs Handbook
description: "A collection of guides and advice to participate in Open Knowledge Labs"
baseurl: "/handbook"
issues_url: http://github.com/okfn/handbook/issues
url: "http://datapatterns.org/"
github_username: okfn
github_repo: handbook
paypal: admin@okfn.org
contact: "https://discuss.okfn.org/c/open-knowledge-labs"
markdown: kramdown 
highlighter: rouge
gems:
  - jekyll-redirect-from
devs:
  -
      name: Dan Fowler
      github: danfowler

      name: Gustavo Silva
      github: gsilvapt

googleanalytics: UA-8271754-43
permalink: pretty
openknowledgeribbon: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      edit: true
